Exception in thread Thread-2 (listen_for_commands):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 64, in listen_for_commands
    command = input().strip().lower()
              ^^^^^^^
EOFError
Traceback (most recent call last):
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 123, in <module>
    input_thread.join()
  File "C:\Python311\Lib\threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "C:\Python311\Lib\threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-06 12:08:20: Error fetching .m3u file: HTTPSConnectionPool(host='www.internet-radio.com', port=443): Max retries exceeded with url: /servers/tools/playlistgenerator/?u=http://uk2.internet-radio.com:8359/listen.pls (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
Exception in thread Thread-2 (listen_for_commands):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 80, in listen_for_commands
    command = input().strip().lower()  # Command entry line
              ^^^^^^^
EOFError
Traceback (most recent call last):
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 154, in <module>
    input_thread.join()
  File "C:\Python311\Lib\threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "C:\Python311\Lib\threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-06 12:08:33: Error fetching .m3u file: HTTPSConnectionPool(host='www.internet-radio.com', port=443): Max retries exceeded with url: /servers/tools/playlistgenerator/?u=http://uk5.internet-radio.com:8270/listen.pls (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
Exception in thread Thread-2 (listen_for_commands):
Traceback (most recent call last):
  File "C:\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 80, in listen_for_commands
    command = input().strip().lower()  # Command entry line
              ^^^^^^^
EOFError
Traceback (most recent call last):
  File "c:\charlie\projects\python\streamdoken\streamdoken.py", line 154, in <module>
    input_thread.join()
  File "C:\Python311\Lib\threading.py", line 1112, in join
    self._wait_for_tstate_lock()
  File "C:\Python311\Lib\threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-09-06 12:09:57: Error fetching .m3u file: HTTPSConnectionPool(host='somafm.com', port=443): Max retries exceeded with url: /groovesalad320.pls (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-09-06 12:10:29: Error fetching .m3u file: HTTPConnectionPool(host='199.189.87.9', port=10999): Max retries exceeded with url: /stream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000026702A3E610>, 'Connection to 199.189.87.9 timed out. (connect timeout=None)'))
2024-09-06 12:10:40: Error fetching .m3u file: HTTPSConnectionPool(host='stream.radioparadise.com', port=443): Max retries exceeded with url: /aac-320 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-09-06 12:12:09: Error fetching .m3u file: HTTPSConnectionPool(host='somafm.com', port=443): Max retries exceeded with url: /groovesalad320.pls (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-09-06 12:12:42: Error fetching .m3u file: HTTPConnectionPool(host='199.189.87.9', port=10999): Max retries exceeded with url: /stream (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001A1F9C8E610>, 'Connection to 199.189.87.9 timed out. (connect timeout=None)'))
2024-09-06 12:14:23: Error fetching .m3u file: HTTPConnectionPool(host='kcrw.streamguys1.com', port=80): Max retries exceeded with url: /kcrw_192k_mp3.m3u (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000233196FE550>: Failed to resolve 'kcrw.streamguys1.com' ([Errno 11001] getaddrinfo failed)"))
2024-09-06 12:18:05: Error fetching .m3u file: HTTPConnectionPool(host='kcrw.streamguys1.com', port=80): Max retries exceeded with url: /kcrw_192k_mp3.m3u (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000021BF282E490>: Failed to resolve 'kcrw.streamguys1.com' ([Errno 11001] getaddrinfo failed)"))
2024-09-06 12:18:08: Error fetching .m3u file: HTTPConnectionPool(host='kcrw.streamguys1.com', port=80): Max retries exceeded with url: /kcrw_192k_mp3.m3u (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000021BF284C7D0>: Failed to resolve 'kcrw.streamguys1.com' ([Errno 11001] getaddrinfo failed)"))
